### DISCUSSION TITLE
빌드 배포 에러

### DISCUSSION THREAD

**Discussion by YeonjuSeo** [devrel-kr/HackaLearn#187] [6 Q&A - 프론트엔드] [answered]
안녕하세요. Azure static web app을 배포하려는 중 지속적으로 Build and Deploy Error가 발생하여 질문 드립니다. 자주 이러한 문제가 발생하는데 해결이 되는 듯 하다가도 다시 에러가 발생하고 있습니다.
저희는 React를 사용하고 있고 Window를 사용하고 있습니다.

### 오류 로그
![image](https://user-images.githubusercontent.com/56028436/129408560-7a971d5a-f2fd-4966-84bf-1993760dbbac.png)

### 1차 해결
https://github.com/microsoft/Oryx/issues/605#issuecomment-632401561 를 참고하여
jobs 속에 `env: CI: false`를 추가하여 1차적으로 문제가 해결한 듯 보였습니다.

그러나 라우팅 작업을 한 뒤 다시 푸쉬를 하니 잘 되던 build&deploy에서 다시 동일한 에러가 발생하기 시작했습니다.
https://github.com/KneeBarista-MyGiftSavor/MyGiftSavor/actions/runs/1128789724

현재 이를 해결하기 위해 해본 것은
1. .github/workflow에 있는 .yml 파일 삭제한 뒤 커밋 후 새로 만들어서 배포 시도(실패)
2. .env 파일을 만들어 커밋 푸쉬 후 배포 시도(실패)
```
//.env
SKIP_PREFLIGHT_CHECK=true
```

### 현재
azure-static-web-apps-black-smoke-070207e10.yml
```
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
      CI: false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_SMOKE_070207E10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_SMOKE_070207E10 }}
          action: "close"

```

원인을 도저히 모르겠습니다...도와주세요!!
