### DISCUSSION TITLE
Azure 정적 웹앱 만들기 Bulid and Deploy Error

### DISCUSSION THREAD

**Discussion by seonghun-dev** [devrel-kr/HackaLearn#66] [2 Q&A - 클라우드 스킬 챌린지] [answered]
안녕하세요.
Azure 정적 웹 앱 만들기 중 Bulid and Deploy Errorr가 나서 문의 드립니다. local 환경에서는 모두 잘 작동합니다. 프레임워크로 Vue를 사용하고 있고, OS는 Window 환경입니다.

### 변경 사항
파일 구조는 기존과 동일하고 추가된 것은 vue-app으로 이용시, #43 와 동일한 Issue가 발생하여

`env: CUSTOM_BUILD_COMMAND: "npm install -g npm && npm install --unsafe-perm && npm run build"
`
다음 내용을 추가했습니다. 추가적인 차이점은 github repository의 이름만 조금 다르게 했습니다.

유사한 Issue에 관해서 찾아보니 [Oryx issues #623](https://github.com/microsoft/Oryx/issues/623) 

> 1. remove everything from my repository except
>   git related files (.gitignore)
>   .github directory
>   directory (i called mines 'pregen') containing html, css, js, gifs, etc
> 
> 2. in the .github/azure-static-web-apps-*.yml file set the app_location to your html directory (I called mines 'pregen')

같은 방식이 있었는데, 이 문제방식을 적용할 경우, vue-app 과 .git 폴더를 남기고 모두 제거해야 하는 것인가요? 아니면 다른 해결 방법이 있는 지 궁금합니다.

### Bulid and Deploy Error Part

> 해당 빌드의 로그 파일 입니다.
> 
> [logs_10.zip](https://github.com/devrel-kr/HackaLearn/files/6944129/logs_10.zip)

![image](https://user-images.githubusercontent.com/80201773/128475223-70e71437-75cf-4155-8897-61cb8440c589.png)

### azure-static-web-apps~~~~~.yml
```yml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_DESERT_07A0EC910 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "vue-app" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_DESERT_07A0EC910 }}
          action: "close"
```
